spring.application.name=auth-service

# --- Puerto del Servidor ---
# Usamos 8080 para el servicio de autenticación (el de análisis usa 8081)
server.port=8080

# --- Configuración de la Base de Datos MySQL ---
# Conexión a AWS RDS (mismo endpoint que microservicio Stats)
spring.datasource.url=jdbc:mysql://securelink.cz53cv2gj6ra.us-east-1.rds.amazonaws.com:3306/bd_securelink?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Tu usuario y contraseña de MySQL
spring.datasource.username=admin
spring.datasource.password=viwge4-zojwam-doXfyp

# Pool de conexiones HikariCP
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.connection-timeout=30000

# --- Configuración de JPA (Hibernate) ---
# Le dice a Spring que estamos usando el "dialecto" de MySQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Hibernate crea/actualiza automáticamente la tabla 'users' basándose en @Entity
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Clave secreta para firmar los JWT (en formato Base64)
jwt.secret=Y2hhbmdlX3RoaXNfc2VjcmV0X2tleV90b19zb21ldGhpbmdfcmFuZG9tX2FuZF9sb25nCg==

# Permitir que un bean sobrescriba a otro (útil para despliegues donde hay definiciones duplicadas)
spring.main.allow-bean-definition-overriding=true
