spring.application.name=analysis-service

server.port=8081

# --- API Keys de Servicios Externos ---
api.google.key=AIzaSyBkzwPBOitKLMKuwxIyTOR-W85LMxQwr6o
api.virustotal.key=001a857bfbf57c6604dc30e1e69276ceb293c4c3570195e2952f0d7d74468019