spring.application.name=analysis-service

server.port=8081

# --- API Keys de Servicios Externos ---
api.google.key=
api.virustotal.key=

# --- Logging Configuration ---
logging.level.root=INFO
logging.level.com.securelink.analysis_service=DEBUG
logging.level.com.securelink.analysis_service.exception=DEBUG

# --- Conexión a la base de datos (misma BD que auth-service) ---
spring.datasource.url=
spring.datasource.username=
spring.datasource.password=

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# JWT secret (debe ser la misma que en auth-service)
jwt.secret=Y2hhbmdlX3RoaXNfc2VjcmV0X2tleV90b19zb21ldGhpbmdfcmFuZG9tX2FuZF9sb25nCg==