
spring.application.name=microservicio-Stats
server.port=8082

# ESTA LÍNEA ES LA CLAVE: Le dice a Spring "No busques base de datos"
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration, org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration